---
- name: Install st2
  hosts: all
  environment: "{{ st2_proxy_env | default({}) }}"
  gather_facts: False
  pre_tasks:
    - name: Install python for Ansible
      become: True
      raw: test -e /usr/bin/python || (apt install -y python-minimal)
      changed_when: False
    - name: Gathering facts
      setup:
  roles:
    - StackStorm.mongodb
    - StackStorm.rabbitmq
    - StackStorm.st2repo
    - StackStorm.st2
    - StackStorm.nginx
    - StackStorm.st2web
    - StackStorm.nodejs
    - StackStorm.st2chatops
    - StackStorm.st2smoketests
    - role: StackStorm.ewc
      when: ewc_license is defined and ewc_license is not none and ewc_license | length > 1
    - role: StackStorm.ewc_smoketests
      when: ewc_license is defined and ewc_license is not none and ewc_license | length > 1
    - role: StackStorm.git
      when: github_token is defined and github_token is not none and github_token | length > 1