bitops:

  ops_repo:
    source:
      sourced_from: local
  
  fail_fast: true
  run_mode: default

  # DEBUG, INFO, WARNING, ERROR
  logging:
    level: DEBUG
    file: bitops.logs
    err: bitops.logs
    
  plugins:
    plugins_seq:
      - terraform-usage1
      - helm
      - terraform-usage2

    tools:
      cloudproviders:
        aws:
          source: 
            sourced_from: https://github.com/bitops-plugins/aws

      deployment:
        terraform-usage1:
          source: 
            sourced_from: https://github.com/bitops-plugins/terraform
        
        terraform-usage2:
          source: 
            sourced_from: https://github.com/bitops-plugins/terraform

        helm:
          source: 
            sourced_from: https://github.com/bitops-plugins/helm
    