bitops:
  
  fail_fast: true
  run_mode: default

  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  logging:
    level: DEBUG
    color:
      enabled: true
    filename: bitops-run
    err: bitops.logs
    path: /var/logs/bitops
    # May need Logging modes to support log aggs like; LogStash, etc
    
  plugins:
    aws:
      source: https://github.com/bitops-plugins/aws
    terraform:
      source: https://github.com/bitops-plugins/terraform
    helm:
      source: https://github.com/bitops-plugins/helm
    kubectl:
      source: https://github.com/bitops-plugins/kubectl
    ansible:
      source: https://github.com/bitops-plugins/ansible
    cloudformation:
      source: https://github.com/bitops-plugins/cloudformation
  # deployments:
  #   terraform:
  #     plugin: terraform
  #   helm:
  #     plugin: helm
  #   cloudformation:
  #     plugin: cloudformation