bitops:

  source:
    sourced_from: local
  
  fail_fast: true
  run_mode: default

  # DEBUG, INFO, WARNING, ERROR
  logging:
    level: DEBUG
    file: bitops.logs
    err: bitops.logs
    color:
      enabled: true
    filename: bitops-run
    path: /var/logs/bitops
    


    
  plugins:
    plugins_seq:
      - terraform-usage1
      - helm
      - terraform-usage2

    tools:
      cloudproviders:
        aws:
          source: 
            sourced_from: https://github.com/bitops-plugins/aws

      deployment:
        terraform-usage1:
          source: 
            sourced_from: https://github.com/bitops-plugins/terraform
          identity: terraform
        
        terraform-usage2:
          source: 
            sourced_from: https://github.com/bitops-plugins/terraform
          identity: terraform

        helm:
          source: 
            sourced_from: https://github.com/bitops-plugins/helm
    