bitops:

  source:
    sourced_from: local
  
  fail_fast: true
  run_mode: default

  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  logging:
    level: DEBUG
    file: bitops.logs
    err: bitops.logs
    color:
      enabled: true
    filename: bitops-run
    path: /var/logs/bitops
    # May need Logging modes to support log aggs like; LogStash, etc
    
  plugins:
    plugins_seq:
      - terraform-usage1
      - helm
      - terraform-usage2

    tools:
      cloudproviders:
        aws:
          source:
            sourced_from: https://github.com/bitops-plugins/aws

      deployment:
        terraform-usage1:
          source: 
            sourced_from: local
            path: /Users/philh/Documents/Bitovi/terraform
          identity: terraform
    