bitops:

  source:
    sourced_from: local
  
  fail_fast: true
  run_mode: default

  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  logging:
    level: DEBUG
    file: bitops.logs
    err: bitops.logs
    color:
      enabled: true
    filename: bitops-run
    path: /var/logs/bitops
    # May need Logging modes to support log aggs like; LogStash, etc
    
  plugins:
    aws:
      source: 
        sourced_from: https://github.com/bitops-plugins/aws
    terraform:
      source: 
        sourced_from: https://github.com/bitops-plugins/terraform
    helm:
      source: 
        sourced_from: https://github.com/bitops-plugins/helm
    kubectl:
      source: 
        sourced_from: https://github.com/bitops-plugins/kubectl
    ansible:
      source: 
        sourced_from: https://github.com/bitops-plugins/ansible
    cloudformation:
      source: 
        sourced_from: https://github.com/bitops-plugins/cloudformation
  deployment-sequence:
    terraform:
      plugin: terraform
    helm:
      plugin: helm
    cloudformation:
      plugin: cloudformation