## Using alpine fails on awscli install
FROM python:3.8.6-alpine
ENV DEBIAN_FRONTEND=noninteractive
RUN apk add --no-cache bash
RUN apk update

RUN apk add \
    libsodium-dev \
    wget \
    unzip \
    git \
    jq \
    curl
    
# install glibc compatibility for alpine
ENV GLIBC_VER=2.31-r0
RUN mkdir -p /opt/bitops

WORKDIR /opt/bitops
COPY . .

RUN pip3 install -r requirements.txt
#RUN bash -x scripts/setup/install_tools.sh
COPY plugin.config.yaml .
ONBUILD RUN python scripts/setup/install_plugins.py