terraform:
  cli:
    stack-action: destroy
    version: test
  options:
    cfn-stack-name: unqiue-stack-name3
    s3-bucket: s3-test-multiregion
    s3-prefix: single-deployment
    cfn-create-bucket: true
    cfn-files:
      template-file: template.yaml
      parameters:
        enabled: true
        template-param-file: parameters.json