terraform:
    cli: 
      backend-config:
        - KEY1=foo
        - KEY2=bar
      init-upgrade: false
    options:
        command: apply
        version: "0.13.2"
        fetch-kubeconfig: false