terraform:
    cli: 
      backend-config:
        - KEY1=foo
          KEY2=bar
        - KEY3=baz
      init-upgrade: true
    options:
        command: apply
        version: "0.13.2"
        fetch-kubeconfig: false