---
- name: Check for 'github_token' environmental variable
  fail:
    msg: "GitHub token environmental variable is required for the git ansible role."
  when: github_token is not defined or github_token is none or github_token|length != 40

- name: Temporarily auth access the data store
  become: true
  no_log: yes
  changed_when: no
  command: st2 login {{ st2_auth_username }} -p {{ st2_auth_password }} -l 60

- name: Add GitHub token to ST2 key-value store
  become: true
  no_log: yes
  changed_when: no
  command: st2 key set github_token {{ github_token }} --encrypt

- name: Set config info
  become: true
  copy:
    dest: "/opt/stackstorm/configs/git.yaml"
    content: |
      ---
      repositories: 
      {% for item in repositories %}
        - url: "{{ item.url }}"
          branch: "{{ item.branch }}"
      {% endfor %}
  notify:
    - reload st2packconfigs
    - restart st2sensors
