ansible:
  type: object
  properties:
    cli:
      type: object
      properties:
        flush-cache:
          type: string
          parameter: flush-cache
          export_env: BITOS_ANSIBLE_FLUSH_CACHE
        force-handlers:
          type: string
          parameter: force-handlers
          export_env: BITOPS_ANSIBLE_FORCE_HANDLERS
        skip-tags:
          type: string
          parameter: skip-tags
          export_env: BITOPS_ANSIBLE_SKIP_TAGS
        forks:
          type: string
          parameter: forks
          export_env: BITOPS_ANSIBLE_FORKS
        inventory:
          type: string
          parameter: inventory
          export_env: BITOPS_ANSIBLE_INVENTORY
        tags:
          type: string
          parameter: tags
          export_env: BITOPS_ANSIBLE_TAGS
        extra-vars:
          type: string
          parameter: extra-vars
          export_env: BITOPS_ANSIBLE_EXTRA_VARS
    options:
      type: object
      properties:
        dryrun:
          type: boolean
          export_env: BITOPS_ANSIBLE_DRYRUN
          default: false
