name: Build and Publish base image

on:
  workflow_dispatch: {}
  push:
    branches: [ plugins ]
    tags:
      - "*"
    paths-ignore:
      - "docs/**"
      - "prebuilt-config/**"
      - ".github/workflows/build-and-publish-prebuilt.yml"
      - ".github/workflows/publish-docs.yml"
      - ".gitignore"
      - "bitops.schema.yaml"
      - "*.md"
      - "mkdocs.yml"
  release:
    types: [ published ]
  
env:
  BASE_TAG: plugins-base-RC
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        
    - name: debugging
      run: |
        echo ${{ github.event_name}}

    # ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~- #
    #                   PUSH                   #
    # ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~- #  
    - name: Publish Docker Image (Push)
      env:
        REGISTRY_URL: "bitovi/bitops"
        DEFAULT_BRANCH: "plugins"
        DOCKER_USER: ${{ secrets.DOCKER_USER}}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS}}
        IMAGE_TAG: ${{ env.BASE_TAG}}
      run: |
        echo "running scripts/ci/publish.sh"
        ./scripts/ci/publish.sh
      if: ${{ github.event_name == "push"}}
    

    # ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~- #
    #           Workflow dispatch              #
    # ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~- # 
    - name: Publish Docker Image (Workflow dispatch)
      env:
        REGISTRY_URL: "bitovi/bitops"
        DEFAULT_BRANCH: "plugins"
        DOCKER_USER: ${{ secrets.DOCKER_USER}}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS}}
        IMAGE_TAG: ${{ env.BASE_TAG}}
      run: |
        echo "running scripts/ci/publish.sh"
        ./scripts/ci/publish.sh
      if: ${{ github.event_name == "workflow_dispatch"}}


    # ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~- #
    #                Release                   #
    # ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~- # 
    - name: Publish Docker Image (Release)
      env:
        REGISTRY_URL: "bitovi/bitops"
        DEFAULT_BRANCH: "plugins"
        DOCKER_USER: ${{ secrets.DOCKER_USER}}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS}}
        IMAGE_TAG: ${{ env.BASE_TAG}}
      run: |
        echo "running scripts/ci/publish.sh"
        ./scripts/ci/publish.sh
      if: ${{ github.event_name == "release"}}


    # Bump the version in `prebuilt-config/bitops-tag
    - name: Bump version tag
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: prebuilt-config/bitops-tag.yaml
        propertyPath: 'tags.bitops-base'
        value: ${{ env.BASE_TAG}}
        commitChange: true
        updateFile: true
