name: Build and Publish

on:
  push:
    branches: [ plugins ]
    tags:
      - "*"
    paths-ignore:
      - "docs/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # TODO: when we have tests
    # - run: |
    #   ./scripts/ci/install.sh
    #   ./scripts/ci/test.sh
    - name: Publish Docker Image
      env:
        REGISTRY_URL: "bitovi/bitops"
        DEFAULT_BRANCH: "plugins"
        DOCKER_USER: ${{ secrets.DOCKER_USER}}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS}}
      run: |
        echo "running scripts/ci/publish.sh"
        ./scripts/ci/publish.sh
