name: Build and Publish base image

on:
  workflow_dispatch: {}
  push:
    branches: [ plugins ]
    tags:
      - "*"
    paths-ignore:
      - "docs/**"
      - "prebuilt-config/**"
      - ".github/workflows/build-and-publish-prebuilt.yml"
      - ".github/workflows/publish-docs.yml"
      - ".gitignore"
      - "bitops.schema.yaml"
      - "*.md"
      - "mkdocs.yml"
  
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        
    - name: Publish Docker Image
      env:
        REGISTRY_URL: "bitovi/bitops"
        DEFAULT_BRANCH: "plugins"
        DOCKER_USER: ${{ secrets.DOCKER_USER}}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS}}
        IMAGE_TAG: base
        IMAGE_PREFIX: plugins
      run: |
        echo "running scripts/ci/publish.sh"
        ./scripts/ci/publish.sh
    
    # Bump the version in `prebuilt-config/bitops-tag
    
