name: Build and Publish

on:
  push:
    branches: [ plugins ]
    tags:
      - "*"
    paths-ignore:
      - "docs/**"
  
jobs:
  publish:
    name: Publish for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        target:
          - kitchen-sink
          - aws+terraform

    steps:
    - uses: actions/checkout@v2

    # Move the dockerfile and bitops.config.yaml into the project root folder
    - name: Copy Dockerfile and bitops.config.yaml into the project root folder
      run: |
        cp ./prebuilt-config/${{ matrix.target }}/Dockerfile ./Dockerfile
        cp ./prebuilt-config/${{ matrix.target }}/bitops.config.yaml ./bitops.config.yaml
    
    # TODO: when we have tests
    # - run: |
    #   ./scripts/ci/install.sh
    #   ./scripts/ci/test.sh
    
    - name: Publish Docker Image
      env:
        REGISTRY_URL: "bitovi/bitops"
        DEFAULT_BRANCH: "plugins"
        DOCKER_USER: ${{ secrets.DOCKER_USER}}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS}}
      run: |
        echo "running scripts/ci/publish.sh"
        ./scripts/ci/publish.sh
