name: Build and Publish preconfigured images

on:
  workflow_dispatch: 
    inputs:
      bitops_tag:
        description: Specifies the tag that will be published
        type: string
        default: plugins
        required: true
  push:
    branches: [ plugins ]
    tags:
      - "*"
    paths:
      - "prebuilt-config/bitops-tag.yaml"
      - ".github/workflows/build-and-publish-prebuilt.yaml"
  
jobs:
  publish-prebuilds:
    name: Publish for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        target:
          - aws-ansible  
          - aws-helm
          - aws-terraform
          - omnibus

    steps:
    - uses: actions/checkout@v2
    
    # ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~- #
    #                   PUSH                   #
    # ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~- # 
    # Loads VERSION_TAG from prebuilt-config/bitops-tag.yaml
    - name: Parse bitops_base from yaml
      id: yaml-data
      uses: KJ002/read-yaml@main
      with:
        file: 'prebuilt-config/bitops-tag.yaml'    
        key-path: '["tags", "plugins_base"]'
      if: github.event_name == 'push'
    
    - name: Update VERSION_TAG with input (Push)
      run: |
        echo "VERSION_TAG=${{ steps.yaml-data.outputs.data }}" >> $GITHUB_ENV
      if: github.event_name == 'push'
    
     # Apply jinja to tag
    - uses: cuchi/jinja2-action@v1.2.0
      with:
        template: prebuilt-config/dockerfile.template
        output_file: prebuilt-config/${{ matrix.target }}/Dockerfile
        data_file: prebuilt-config/bitops-tag.yaml
        data_format: yaml
      if: github.event_name == 'push'
  
    # ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~- #
    #           Workflow dispatch              #
    # ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~- # 
    # Loads VERSION_TAG from inputs
    - name: Update VERSION_TAG with input (workflow_disbatch)
      run: |
        echo "VERSION_TAG=${{ github.event.inputs.bitops_base_tag}}" >> $GITHUB_ENV
      if: github.event_name == 'workflow_disbatch'
    
    - uses: cuchi/jinja2-action@v1.2.0
      with:
        template: prebuilt-config/dockerfile.template
        output_file: prebuilt-config/${{ matrix.target }}/Dockerfile
        strict: true
        variables: |
          bitops_base=${{ env.VERSION_TAG }}
      if: github.event_name == 'workflow_disbatch'

    # ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~- #
    #                   ALL                    #
    # ~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~-~- # 
    # Move the dockerfile and bitops.config.yaml into the project root folder
    - name: Copy Dockerfile and bitops.config.yaml into the project root folder
      run: |
        cp ./prebuilt-config/${{ matrix.target }}/Dockerfile ./Dockerfile
        cp ./prebuilt-config/${{ matrix.target }}/bitops.config.yaml ./bitops.config.yaml
                
    - name: Publish Docker Image
      env:
        REGISTRY_URL: "bitovi/bitops"
        DEFAULT_BRANCH: "plugins"
        DOCKER_USER: ${{ secrets.DOCKER_USER}}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS}}
        IMAGE_TAG: ${{ env.VERSION_TAG }}-${{ matrix.target }}
      run: |
        echo "running scripts/ci/publish.sh"
        ./scripts/ci/publish.sh
