name: Build and Publish preconfigured images

on:
  workflow_dispatch: {}
  push:
    branches: [ plugins ]
    tags:
      - "*"
    paths:
      - "prebuilt-config/bitops-tag"
  
jobs:
  publish:
    name: Publish for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        target:
          - KitchenSink
          - AwsTerraform
          - AwsAnsible
          - AwsTerraformHelm

    steps:
    - uses: actions/checkout@v2
    
    # Apply jinja to tag
    - uses: cuchi/jinja2-action@v1.2.0
      with:
        template: prebuilt-config/dockerfile.template
        output_file: prebuilt-config/${{ matrix.target }}/Dockerfile
        data_file: prebuilt-config/bitops-tag
        data_format: yaml

    # Move the dockerfile and bitops.config.yaml into the project root folder
    - name: Copy Dockerfile and bitops.config.yaml into the project root folder
      run: |
        cp ./prebuilt-config/${{ matrix.target }}/Dockerfile ./Dockerfile
        cp ./prebuilt-config/${{ matrix.target }}/bitops.config.yaml ./bitops.config.yaml
        
    - name: Publish Docker Image
      env:
        REGISTRY_URL: "bitovi/bitops"
        DEFAULT_BRANCH: "plugins"
        DOCKER_USER: ${{ secrets.DOCKER_USER}}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS}}
        IMAGE_TAG: ${{ matrix.target }}
        IMAGE_PREFIX: plugins
      run: |
        echo "running scripts/ci/publish.sh"
        ./scripts/ci/publish.sh